"use strict";
const faker = require("faker");

module.exports = {
	up: (queryInterface, Sequelize) => {
		return queryInterface.bulkInsert(
			"Events",
			[
				{
					name: "1 Casual Hangout",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: "https://cdn.pixabay.com/photo/2019/02/11/11/53/cat-3989479__340.jpg",
				},
				{
					name: "1 Casual Cooking",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "1 Casual Experimentation",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "1 Casual Eating",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "1 Hardcore Hangout",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: "https://cdn.pixabay.com/photo/2019/02/11/11/53/cat-3989479__340.jpg",
				},
				{
					name: "1 Hardcore Cooking",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "1 Hardcore Experimentation",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "1 Hardcore Eating",
					hostId: 4,
					groupId: 1,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "2 Casual Hangout",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: "https://cdn.pixabay.com/photo/2019/02/11/11/53/cat-3989479__340.jpg",
				},
				{
					name: "2 Casual Cooking",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "2 Casual Experimentation",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "2 Casual Eating",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "2 Hardcore Hangout",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: "https://cdn.pixabay.com/photo/2019/02/11/11/53/cat-3989479__340.jpg",
				},
				{
					name: "2 Hardcore Cooking",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "2 Hardcore Experimentation",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "2 Hardcore Eating",
					hostId: 4,
					groupId: 2,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "3 Casual Hangout",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: "https://cdn.pixabay.com/photo/2019/02/11/11/53/cat-3989479__340.jpg",
				},
				{
					name: "3 Casual Cooking",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "3 Casual Experimentation",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "3 Casual Eating",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "3 Hardcore Hangout",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "3 Hardcore Cooking",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "cook off",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "3 Hardcore Experimentation",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
				{
					name: "3 Hardcore Eating",
					hostId: 4,
					groupId: 3,
					location: faker.address.streetAddress(),
					description: faker.lorem.paragraph(),
					eventDate: faker.date.soon(),
					eventType: "experimentation",
					availableSpots: faker.random.number(),
					imgURL: faker.image.imageUrl(),
				},
			],
			{}
		);
	},

	down: (queryInterface, Sequelize) => {
		return queryInterface.bulkDelete("Events", null, {});
	},
};
